name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: apple boy ssh 
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ubuntu
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: |
                export NVM_DIR="$HOME/.nvm"
                source "$NVM_DIR/nvm.sh"
                #source "$NVM_DIR/bash_completion"  # Optional but helps with nvm commands
                #nvm use default  # Ensure you're using the correct Node.js version
                #export PATH="$HOME/.local/share/pnpm:$PATH"
                
                cd 2d-metaverse
                git pull origin main
                echo "DATABASE_URL=${{ secrets.PROD_DATABASE_URL }}" >> packages/db/.env
                echo "VITE_API=http://${{ secrets.PROD_HOST }}:${{ secrets.BACKEND_PORT }}" >> apps/frontend/.env
                echo "PORT=${{ secrets.BACKEND_PORT }}" >> apps/http-server/.env
                echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> apps/http-server/.env
                pnpm install
                pnpm run build
                pm2 restart all
