name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: apple boy ssh 
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ubuntu
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: |
                export NVM_DIR="$HOME/.nvm"
                source "$NVM_DIR/nvm.sh"
                source "$NVM_DIR/bash_completion"  # Optional but helps with nvm commands
                nvm use default  # Ensure you're using the correct Node.js version
                export PATH="$HOME/.local/share/pnpm:$PATH"
                
                cd 2d-metaverse
                git pull origin main
                pnpm install
      # - name: Setting up SSH key
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa

      # - name: Add known host
      #   run: |
      #     echo "${{ secrets.KNOWN_HOST }}" >> ~/.ssh/known_hosts
      #     cat ~/.ssh/known_hosts
      # - name: Copying
      #   run: |
      #     ssh -i ~/.ssh/id_rsa -T ${{ secrets.USER }}@${{ secrets.PROD_HOST }} << 'EOF'
      #       cd /home/ubuntu/2d-metaverse
      #       git pull origin main
      #       pnpm install
      #     EOF
      # - name: Adding env in Database
      #   run: |
      #     echo "DATABASE_URL=${{ secrets.PROD_DATABASE_URL }}" >> packages/db/.env

      # - name: Adding env in frontend,backend
      #   run: |
      #     echo "VITE_API=http://${{ secrets.PROD_HOST }}:${{ secrets.BACKEND_PORT }}" >> apps/frontend/.env
      #     echo "PORT=${{ secrets.BACKEND_PORT }}" >> apps/http-server/.env
      #     echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> apps/http-server/.env
