name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.9.0
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install
      
      - name: Setting up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add known host
        run: |
          echo "${{ secrets.KNOWN_HOST }}" >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Adding env in Database
        run: |
          echo "DATABASE_URL=${{ secrets.PROD_DATABASE_URL }}" >> packages/db/.env

      - name: Adding env in frontend,backend
        run: |
          echo "VITE_API=http://${{ secrets.PROD_HOST }}:${{ secrets.BACKEND_PORT }}" >> apps/frontend/.env
          echo "PORT=${{ secrets.BACKEND_PORT }}" >> apps/http-server/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> apps/http-server/.env

      - name: Build frontend, backend
        run: pnpm run build
      
      - name: Compressing
        run: tar -czf apps.tar.gz apps

      - name: Copying
        run: |
          scp -i ~/.ssh/id_rsa apps.tar.gz ${{secrets.USER}}@${{ secrets.PROD_HOST }}
          ssh -i ~/.ssh/id_rsa -T ${{ secrets.USER }}@${{ secrets.PROD_HOST }} << 'EOF'
            mkdir hello
            ls
            rm -rf hello
          EOF